"""empty message

Revision ID: 7e7832c2e4d8
Revises: c077b0bf3ffa
Create Date: 2021-12-30 15:22:43.577514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7e7832c2e4d8"
down_revision = "c077b0bf3ffa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ssms_student", sa.Column("scholarship", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ssms_student", "scholarship")
    # ### end Alembic commands ###
