"""empty message

Revision ID: 88b7be0076d6
Revises: 7e7832c2e4d8
Create Date: 2021-12-30 15:23:59.467488

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column


# revision identifiers, used by Alembic.
revision = "88b7be0076d6"
down_revision = "7e7832c2e4d8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    scholarship = table("ssms_student", column("scholarship"))
    fees_paid_in_full = table("ssms_student", column("fees_paid_in_full"))
    op.execute(scholarship.update().values(scholarship=False))
    op.execute(fees_paid_in_full.update().values(fees_paid_in_full=False))
    op.alter_column(
        "ssms_student", "fees_paid_in_full", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column(
        "ssms_student", "scholarship", existing_type=sa.BOOLEAN(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ssms_student", "scholarship", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "ssms_student", "fees_paid_in_full", existing_type=sa.BOOLEAN(), nullable=True
    )
    # ### end Alembic commands ###
