"""empty message

Revision ID: c077b0bf3ffa
Revises: 6cdf2e419097
Create Date: 2021-12-30 14:25:33.747043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c077b0bf3ffa"
down_revision = "6cdf2e419097"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ssms_fees", sa.Column("date_created", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ssms_fees", "date_created")
    # ### end Alembic commands ###
